version: "3.8"

services:

  backend:
    depends_on: 
      - db
    build: ./backend
    ports: 
      - 4000:4000
    env_file:
      - ./backend/.env
    command: ["npm", "start"]
    volumes:
      - ./backend/src:/app/src
      - ./backend/config:/app/config

  frontend:
    depends_on: 
      - backend
    build: ./frontend
    ports:
      - 3000:3000
    command: ["npm", "start"]
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public

  db:
    image: mongo:4.0-xenial
    ports:
      - 27018:27017
    volumes:
      - gyst:/data/db

volumes:
  gyst:
